print('hello')
print('\r\n')
print('\r\n')
print('here\'s a picture of a dog:')
print(' o____')
print('  ||||')
print('\r\n')
print('\r\n')
print('My favourite animals are sheep')
print(' o-###-')
print('  |  |  #')
print('\r\n')
print('I live in Toronto')
print('\r\n')
print('  _|_')
print(' |   |')
print(' |#  |')
print(' |   |____')
print(' |  #|  # |')
print('_|___|____|_')
print('\r\n')
print('\r\n')
print('Here is a scarf:')
print('~#' * 10)
print('#-' * 10)
print('Here is a wave')
print('/\  ' * 10)
print('  \/' * 10)